/**
 * Reads a System Intelligence "canonical snapshot" directory -- the ONLY documented,
 * working, decoupled export contract `kajisho5/system-intelligence` has today
 * (`Snapshot.write_to_directory`, its own `core/snapshot.py`): a `manifest.json` plus
 * one JSON array file per collection (`findings.json`, `recommendations.json`,
 * `research.json`, `verification.json`, `approvals.json`, `components.json`,
 * `capabilities.json`, `relationships.json`).
 *
 * This module does NOT import or duplicate System Intelligence's own analysis logic --
 * it only reads the plain JSON files that tool's own CLI (`si diagnose --out DIR`,
 * `si report --out DIR`, `si inspect --out DIR`) already writes, verbatim, field names
 * preserved as SI defines them (Pydantic `model_dump(mode="json")`).
 *
 * As of this writing, `recommendations.json`, `research.json`, `verification.json`
 * and `approvals.json` will always be empty arrays -- those pipeline stages are
 * documented stubs upstream, not a gap in this adapter. `findings.json` is the one
 * collection with real data once a snapshot has actually been generated.
 *
 * No snapshot directory is bundled with or generated by this repository -- the
 * Control Room only reads one if the person running it points `SI_SNAPSHOT_DIR` at
 * one they generated themselves by running System Intelligence against a target.
 * Its complete absence is reported honestly, never silently treated as "0 findings."
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import type { IntelligenceFinding, IntelligenceRecommendation, SystemIntelligenceStatus } from "../types.js";

interface SiEvidence {
  id: string;
  kind: string;
  source: string;
  locator: string | null;
  observation: string;
  confidence: string;
  observed_at: string;
}

interface SiFinding {
  id: string;
  category: string;
  severity: string;
  statement: string;
  confidence: string;
  affected_entity_ids: string[];
  evidence: SiEvidence[];
  suggested_actions: string[];
}

interface SiRecommendation {
  id: string;
  objective: string;
  rationale: string;
  confidence: string;
}

function readJsonArray<T>(dir: string, filename: string): T[] {
  const filePath = path.join(dir, filename);
  if (!existsSync(filePath)) return [];
  try {
    const parsed = JSON.parse(readFileSync(filePath, "utf-8"));
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch {
    return [];
  }
}

export function loadSystemIntelligenceSnapshot(snapshotDir: string | undefined): SystemIntelligenceStatus {
  if (!snapshotDir) {
    return { available: false, snapshotDirectory: null, reason: "SI_SNAPSHOT_DIR not set -- no System Intelligence snapshot configured", findings: [], recommendations: [], researchCount: 0, verificationCount: 0 };
  }
  if (!existsSync(path.join(snapshotDir, "manifest.json"))) {
    return { available: false, snapshotDirectory: snapshotDir, reason: `no manifest.json found at ${snapshotDir} -- not a valid System Intelligence snapshot directory`, findings: [], recommendations: [], researchCount: 0, verificationCount: 0 };
  }

  const siFindings = readJsonArray<SiFinding>(snapshotDir, "findings.json");
  const siRecommendations = readJsonArray<SiRecommendation>(snapshotDir, "recommendations.json");
  const research = readJsonArray<unknown>(snapshotDir, "research.json");
  const verification = readJsonArray<unknown>(snapshotDir, "verification.json");

  const findings: IntelligenceFinding[] = siFindings.map((f) => ({
    id: f.id,
    category: f.category,
    severity: f.severity,
    statement: f.statement,
    confidence: f.confidence,
    affectedEntityIds: f.affected_entity_ids,
    evidence: f.evidence.map((e) => ({ source: "si_snapshot" as const, locator: e.locator ?? e.source, detail: e.observation })),
  }));
  const recommendations: IntelligenceRecommendation[] = siRecommendations.map((r) => ({ id: r.id, objective: r.objective, rationale: r.rationale, confidence: r.confidence }));

  return {
    available: true,
    snapshotDirectory: snapshotDir,
    reason: `loaded: ${findings.length} finding(s), ${recommendations.length} recommendation(s), ${research.length} research result(s), ${verification.length} verification record(s)`,
    findings,
    recommendations,
    researchCount: research.length,
    verificationCount: verification.length,
  };
}
